num1=int(input("Digite o primeiro número:"))
num2=int(input("Digite o segundo número:"))
num3=int(input("Digite o terceiro número:"))
som1=(num1+num2)
som2=(num3+num2)
print("O resultado da soma de",num1,"+",num2,"é",som1)
print("O resultado da soma de",num3,"+",num2,"é",som2)
print("O resultado da multiplicação desses numeros",som2*som1)
